version: "3.7"

services:
  # app:
  #   build: ./
  #   environment:
  #     DB_HOST: localhost
  #     DB_PORT: 5432
  #     DB_USER: avito
  #     DB_PASS: avito
  #     DB_NAME: avito
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: avito
      POSTGRES_DB: avito
      POSTGRES_PASSWORD: avito
    ports:
      - 5432:5432
