"""initial migration

Revision ID: adf11f10cbdb
Revises:
Create Date: 2025-02-13 21:02:28.236860

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = 'adf11f10cbdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    items_table=op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_from_id', sa.Uuid(), nullable=False),
    sa.Column('user_to_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    items = [
        {"id": uuid.uuid4(), "type": "t-shirt", "price": 80},
        {"id": uuid.uuid4(), "type": "cup", "price": 20},
        {"id": uuid.uuid4(), "type": "book", "price": 50},
        {"id": uuid.uuid4(), "type": "pen", "price": 10},
        {"id": uuid.uuid4(), "type": "powerbank", "price": 200},
        {"id": uuid.uuid4(), "type": "hoody", "price": 300},
        {"id": uuid.uuid4(), "type": "umbrella", "price": 200},
        {"id": uuid.uuid4(), "type": "socks", "price": 10},
        {"id": uuid.uuid4(), "type": "wallet", "price": 50},
        {"id": uuid.uuid4(), "type": "pink-hoody", "price": 500},
    ]

    op.bulk_insert(items_table, items)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('deals')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
