class InvalidJWT(Exception): ...


class InvalidCredentials(Exception): ...


class AlreadyExists(Exception): ...


class InsufficientFunds(Exception): ...


class UserDoesntExists(Exception): ...


class ItemDoesntExists(Exception): ...


class NegativeTransactionAmount(Exception): ...


class IncorrectReceiverCredential(Exception): ...
